USE TimShoes;
GO

SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
SET LOCK_TIMEOUT 15000;

BEGIN TRAN;
    UPDATE Orders.Orders
    SET OrderRequestedDate = '40000101'
    WHERE OrderID = 1;
COMMIT;

SELECT * FROM Orders.Orders;
